name			       'adobe_acrobat_pro'
maintainer       'Wesleyan University'
maintainer_email 'software@wesleyan.edu'
license          'Apache 2.0'
description      'Installs Adobe Acrobat Pro XI'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.5.2'
depends			     'dmg'
depends          'dock'
depends			     'launch_association'
