name			 'videolan_vlc'
maintainer       'Wesleyan University'
maintainer_email 'software@wesleyan.edu'
license          'All rights reserved'
description      'Installs VLC and registers file associations'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.7.0'
depends			 'dmg'
depends          'dock'
depends          'launch_association'
depends          'windows'
