name			       'videolan_vlc'
maintainer       'Wesleyan University'
maintainer_email 'software@wesleyan.edu'
license          'Apache 2.0'
description      'Installs VLC and registers file associations'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.7.0'
depends			     'dmg'
depends          'dock'
depends          'launch_association'
depends          'windows'
