driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[rabbitmq::default]