driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: centos-5.10
  - name: centos-6.4
  - name: fedora-19
  - name: ubuntu-10.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: fake::default
  - name: create
    run_list: fake::create
