name "production"
description "This is our production environment, it is for recipes and cookbooks that have been thoroughly tested for bugs and regressions"
cookbook_versions 	"adobe_air" => "<= 0.2.1",
					"apple_compressor" => "<= 0.4.0",
					"apple_final_cut_pro" => "<= 0.5.0",
					"adobe_flash_player" => "<= 0.6.2",
					"apple_itunes" => "<= 0.4.4",
					"apple_logic_pro" => "<= 0.2.1",
					"apple_osx_updates" => "<= 0.4.2",
					"apple_remote_desktop_client" => "<= 0.2.0",
					"apple_remote_desktop_admin" => "<= 0.2.1",
				    "apple_safari" => "<= 0.4.0",
				    "apple_xcode" => "<= 0.5.0",
				    "chef_chefclient" => "<= 0.4.0",
				    "eset_nod32" => "<= 0.2.0",
				    "google_chrome" => "<= 0.6.2",
				    "hamrick_vuescan" => "<= 0.4.1",
				    "homebrew" => "<= 1.5.4",
				    "kintekcorp_kintek_exploer" => "<= 0.1.0",
				    "mathworks_matlab" => "<= 0.2.0",
				    "microsoft_skype" => "<= 0.3.1",
					"mozilla_firefox" => "<= 0.4.11",
					"prepare" => "<= 0.1.0",
					"printers" => "<= 0.6.1",
					"wacom_tablet" => "<= 0.1.0",
					"xorg_xquartz" => "<= 0.2.0"
