name             'rstudio'
maintainer       'Wesleyan University'
maintainer_email 'software@wesleyan.edu'
license          'Apache 2.0'
description      'Installs RStudio'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.4.1'
depends          'dmg'
depends          'dock'
depends          'windows'